pipeline {
    agent any

    tools {
        nodejs 'NodeJS-22'
    }

    stages {
        stage('Install') {
            steps {
                dir('hello_world-node') {
                    sh 'npm install'
                }
            }
        }

        stage('Run') {
            steps {
                dir('hello_world-node') {
                    sh 'npm start'
                }
            }
        }
    }
}