pipeline {
    agent {
      docker { image 'node:16-alpine'}
    }
    stages {
        stage('Install') {
            steps {
                dir('hello_world-node') {
                    sh 'npm install'
                }
            }
        }

        stage('check Node.js version') {
            steps {
                dir('hello_world-node') {
                    sh 'node -v'
                }
            }
        }

        stage('check npm version') {
            steps {
                dir('hello_world-node') {
                    sh 'npm -v'
                }
            }
        }

        stage('docker check') {
            steps {
                dir('hello_world-node') {
                    sh 'docker -v'
                }
            }
        }

        stage('Run') {
            steps {
                dir('hello_world-node') {
                    sh 'npm start'
                }
             }
        }
    }
}