pipeline {
    agent {
      docker { image 'node:16-alpine'}
    }
    stages {
        stage('Install') {
            steps {
                dir('hello_world-node') {
                    sh 'npm install'
                }
            }
        }

        stage('Run') {
            steps {
                dir('hello_world-node') {
                    sh 'npm start'
                }
            }
        }
    }
}